env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:ava/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: script
rules:
  space-before-function-paren: 
    - error
    - always
  strict:
  - error
  - global
  max-len: 0
